name: notea_frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  quiver: ^3.2.1
  uuid: ^3.0.7
  http: ^0.13.6
  connectivity_plus: ^4.0.1
  progress_state_button: ^1.0.4

  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  multi_select_flutter: ^4.1.3
  intl: ^0.18.1
  path_provider: ^2.0.15
  flutter_rich_text_editor: ^0.0.1
  flutter_quill: ^7.2.0
  file_picker: ^5.3.1
  html_editor_enhanced: ^2.5.1
  rich_editor: ^0.0.6
  speech_to_text: ^6.1.1
  google_ml_kit: ^0.15.0
  animated_text_kit: ^4.2.2
  universal_io: ^2.2.0
  quill_html_editor: ^2.1.9
  flutter_zoom_drawer: ^3.1.1
  provider: ^6.0.5
  flutter_local_notifications: ^15.1.0+1
  flutter_image_compress: ^2.0.3
  #universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
